# Generated by Django 5.0.4 on 2024-05-09 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Provider')),
                ('provider_type', models.IntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], verbose_name='Provider type')),
                ('dept', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Dept')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('parent_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.provider', verbose_name='Parent provider')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('home', models.CharField(max_length=50, verbose_name='Home')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='provider.provider')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
