# Generated by Django 5.0.4 on 2024-05-09 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Provider')),
                ('provider_type', models.IntegerField(choices=[(1, 'Завод'), (2, 'Розничная сеть'), (3, 'Индивидуальный предприниматель')], verbose_name='Provider type')),
                ('dept', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Dept')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('parent_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.provider', verbose_name='Parent provider')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
    ]
